[package]
name = "yukina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.81", features = ["backtrace"] }
chrono = "0.4.35"
clap = { version = "4.5.3", features = ["derive"] }
parse-size = "1.0.0"
regex = "1.10.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
test-log = { version = "0.2.14", default-features = false, features = ["trace"] }
