name: Rust

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git
          target
        key: musl-cargo-${{ hashFiles('**/Cargo.toml') }}
    - name: Test & Compile
      run: |
        mkdir -p ~/.cargo/{git,registry}
        docker run --rm -t \
            --mount type=bind,source=${{ github.workspace }},target=/volume \
            --mount type=bind,source=$HOME/.cargo/registry,target=/root/.cargo/registry \
            --mount type=bind,source=$HOME/.cargo/git,target=/root/.cargo/git \
            --network=host \
            clux/muslrust:stable \
            cargo test
        docker run --rm -t \
            --mount type=bind,source=${{ github.workspace }},target=/volume \
            --mount type=bind,source=$HOME/.cargo/registry,target=/root/.cargo/registry \
            --mount type=bind,source=$HOME/.cargo/git,target=/root/.cargo/git \
            --network=host \
            clux/muslrust:stable \
            cargo build --release
        sudo chown -R runner ~/.cargo/
        sudo chown -R runner target/

    - name: Deploy - Create and Upload Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          target/x86_64-unknown-linux-musl/release/yukina
          target/x86_64-unknown-linux-musl/release/kv
    - name: Deploy - Put it in artifact (if not a tag)
      if: false == startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: yukina
        path: |
          target/x86_64-unknown-linux-musl/release/yukina
          target/x86_64-unknown-linux-musl/release/kv
